// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['handler']['UpdateHandler']['CheckForUpdate']();
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['handler']['UpdateHandler']['DownloadAndInstallUpdate'](arg1);
}
