// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CheckForUpdate():Promise<service.UpdateInfo>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;
